### ISSUE TITLE
couldn't find file 'foundation-datetimepicker' with type 'application/javascript'

### ISSUE THREAD

**Issue by rubinoneroweb** [aliibrahim/foundation-datetimepicker-rails#19]
The above error messages appears in my page after having update the gem to the latest version, the one installed from github. The line causing the error is the very inclusion of the js file in application.js:
`//= require foundation-datetimepicker`

Previous version of the gem (the one from rubygems) works.

**Comment by DenisRichartz** [comment]
I have the same problem you do, but besides the js file the `@import` for styles doesnt work either.

The rubygems version works fine though.

**Comment by aliibrahim** [comment]
@rubinoneroweb @DenisRichartz  thanks for reporting. I have published a new minor version of the gem to rubygems that contains support for Italian language. Please test now and let me know if you run into any issues?

**Comment by DenisRichartz** [comment]
The rubygems version stills work fine for me, no issues loading the js nor css.

But it seems that some options do not work correctly, i can for example change the language to 'zh' and that works, but if i try to change the language to 'ru' or 'it' it just keeps the english descriptions.

**Comment by rubinoneroweb** [comment]
Same to me: Ruby gems version works but no italian translation.
Il 04 mag 2016 11:54 AM, "Denis Richartz" <notifications@github.com> ha
scritto:

**Comment by aliibrahim** [comment]
Can you guys try now with the latest `0.2.3` version on rubygems?

**Comment by DenisRichartz** [comment]
The update to 0.2.3 is now causing the 
`File to import not found or unreadable: foundation-datetimpicker` error

**Comment by rubinoneroweb** [comment]
Same error here
Il 04 mag 2016 1:12 PM, "Denis Richartz" <notifications@github.com> ha
scritto:

**Comment by aliibrahim** [comment]
Ok guys! sorry about that, try with `0.2.4`. Should work now!

**Comment by DenisRichartz** [comment]
Works fine now, 'ru' and 'it' too.

**Comment by rubinoneroweb** [comment]
It now works beautifully, Italian translation as well. Thanks!

**Comment by aliibrahim** [comment]
Great! Closing the issue 👍
